### ISSUE TITLE
received 400 HTTP response

### ISSUE THREAD

**Issue by kidzrockboom** [voussoir/timesearch#11]
Sorry if this isn't detailed enough, I'm new to writing Issues but when I try to run the code I get this error and I have tried reinstalling and checked the bot.py info and checked google and tried to read the code and still cant figure out what is wrong can someone please help. 
(venv) C:\Users\richa\PycharmProjects\timesearch>python timesearch.py get_submissions -r aww
Thank you Jason Baumgartner of Pushshift.io!
Traceback (most recent call last):
  File "timesearch.py", line 424, in <module>
    raise SystemExit(main(sys.argv[1:]))
  File "timesearch.py", line 411, in main
    return betterhelp.subparser_main(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\voussoirkit\betterhelp.py", line 204, in subparser_main
    return subparser_betterhelp(parser, main_docstring, sub_docstrings)(main)(argv)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\voussoirkit\betterhelp.py", line 184, in wrapped
    return main(argv)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\voussoirkit\betterhelp.py", line 203, in main
    return args.func(args)
  File "timesearch.py", line 334, in get_submissions_gateway
    get_submissions.get_submissions_argparse(args)
  File "C:\Users\richa\PycharmProjects\timesearch\timesearch_modules\get_submissions.py", line 99, in get_submissions_argparse
    return get_submissions(
  File "C:\Users\richa\PycharmProjects\timesearch\timesearch_modules\get_submissions.py", line 73, in get_submissions
    for chunk in submissions:
  File "C:\Users\richa\PycharmProjects\timesearch\timesearch_modules\common.py", line 78, in generator_chunker
    for item in generator:
  File "C:\Users\richa\PycharmProjects\timesearch\timesearch_modules\pushshift.py", line 243, in supplement_reddit_data
    live_copies = list(common.r.info(ids))
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 631, in generator
    for result in self.get(API_PATH["info"], params=params):
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 566, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 667, in _objectify_request
    self.request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 849, in request
    return self._core.request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 328, in request
    return self._request_with_retries(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 226, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 183, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 281, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 254, in refresh
    self._request_token(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 400 HTTP response

**Comment by voussoir** [comment]
Hi,

I know that debugging oauth can be a pain because the 400s can be mysterious.

Here's where I get the variables to begin with:

![image](https://user-images.githubusercontent.com/7299570/124400063-a9825300-dcd4-11eb-80ca-ad403b41b82f.png)

Now, in [this script](https://praw.readthedocs.io/en/latest/tutorials/refresh_token.html) it tells you to do some `export praw_client_id=...`, but I actually don't like dealing with environment variables, so an alternative is to just edit the script itself, and add `client_id` and `client_secret` arguments to the `praw.Reddit`:

![image](https://user-images.githubusercontent.com/7299570/124400086-d0408980-dcd4-11eb-8502-74da33682a4c.png)

When I run that script I get this:

![image](https://user-images.githubusercontent.com/7299570/124400034-5c9e7c80-dcd4-11eb-8f82-0ce900c496db.png)

It works:

![image](https://user-images.githubusercontent.com/7299570/124400200-8f954000-dcd5-11eb-8ce4-6325d83618df.png)

I hope that helps a bit.

**Comment by kidzrockboom** [comment]
This was very helpful I was able to see the point of the error. I happened when I tried to run  _r.user.me()_ 

>>> import bot
>>> r = bot.login()
>>> r.user.me()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\models\user.py", line 155, in me
    user_data = self._reddit.get(API_PATH["me"])
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 566, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 667, in _objectify_request
    self.request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\praw\reddit.py", line 849, in request
    return self._core.request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 328, in request
    return self._request_with_retries(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 226, in _request_with_retries
    response, saved_exception = self._make_request(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 183, in _make_request
    response = self._rate_limiter.call(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\rate_limit.py", line 33, in call
    kwargs["headers"] = set_header_callback()
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\sessions.py", line 281, in _set_header_callback
    self._authorizer.refresh()
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 254, in refresh
    self._request_token(
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 155, in _request_token
    response = self._authenticator._post(url, **data)
  File "C:\Users\richa\PycharmProjects\timesearch\venv\lib\site-packages\prawcore\auth.py", line 38, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 400 HTTP response

**Comment by voussoir** [comment]
Yes, the error occurs there because that's the moment where the `r` object needs to actually log in to reddit in order to figure out who it is. Something's wrong with your refresh token so the authorization failed at that moment.

It is difficult for me to know exactly which part of your bot.py file is messed up, but I have demonstrated that the process works. So I would suggest deleting the bot.py that you have and starting from scratch. Here are some additional thoughts:

- Maybe you accidentally made two copies of bot.py in different places, and the one you're editing is not the one being run by the program (so it's still trying to use "xxx").
- I am using Praw v5.2.0. If you're using a higher version then maybe something is different but I expect that's not the case.
- Make sure you don't miss any letters while copy-pasting the refresh token.

**Comment by kidzrockboom** [comment]
Sorry but where am I copying and pasting the refresh token to?

**Comment by voussoir** [comment]
Into bot.py, `APP_REFRESH`

![image](https://user-images.githubusercontent.com/7299570/124400200-8f954000-dcd5-11eb-8ce4-6325d83618df.png)

By the way, `CONTACT_INFO` is used when downloading from pushshift because stuck_in_the_matrix [requests it](https://www.reddit.com/r/pushshift/comments/c5yr9l/i_had_to_ban_a_couple_ips_that_were_making/). You should put an email or something there. The `USERAGENT` could be "/u/kidzrockboom using timesearch".

**Comment by kidzrockboom** [comment]
I tried everything you suggested and then some, would it be possible to mail you my bot.py file so you can test it and see what the issue is?. I am running Praw 7.3.0

**Comment by voussoir** [comment]
Sure, email to `ethan@voussoir.net`

**Comment by kidzrockboom** [comment]
''' bot.py template for PRAW4
This file will be imported by all bots, and provides a standard way to log in.
You should never place this file in a git repository or any place where it will
get shared.
The requirements for this file are:
1   A function `anonymous` with no arguments, which returns a `praw.Reddit`
    instance that has a Useragent but is otherwise anonymous / unauthenticated.
    This will be used in bots that need to make requests but don't need any
    permissions.
2   A function `login` with optional parameter `r`, which returns an
    authenticated Reddit instance.
    If `r` is provided, authenticate it.
    If not, create one using `anonymous` and authenticate that.
    Either way, return the instance when finished.
The exact workings of these functions, and the existence of any other variables
and functions are up to you.
I suggest placing this file in a private directory and adding that directory to
your `PYTHONPATH` environment variable. This makes it importable from anywhere.
However, you may place it in your default Python library. An easy way to find
this is by importing a standard library module and checking its location:
>>> import os
>>> os
<module 'os' from 'C:\\Python36\\lib\\os.py'>
But placing the file in the standard library means you will have to copy it over
when you upgrade Python.
If you need multiple separate bots, I would suggest creating copies of this file
with different names, and then using `import specialbot as bot` within the
application, so that the rest of the interface can stay the same.

'''


import praw

# https://praw.readthedocs.io/en/latest/tutorials/refresh_token.html
CONTACT_INFO = ***@***.***'
USERAGENT = "/u/kidzrockboom"
APP_ID = 'bGPIREYeq13E1w'
APP_SECRET = 'ZEbPhyE2Lf6QyGP6aqMbHtjg5vig3Q'
APP_URI = ''
APP_REFRESH = 'http://localhost:8080'


def anonymous():
    r = praw.Reddit(
        user_agent=USERAGENT,
        client_id=APP_ID,
        client_secret=APP_SECRET,
    )
    return r


def login(r=None):
    new_r = praw.Reddit(
        user_agent=USERAGENT,
        client_id=APP_ID,
        client_secret=APP_SECRET,
        refresh_token=APP_REFRESH,
    )
    if r:
        r.__dict__.clear()
        r.__dict__.update(new_r.__dict__)
    return new_r

    On Monday, 5 July 2021, 00:53:18 GMT+1, Ethan Dalool ***@***.***> wrote:  
 
 


Sure, email to ***@***.***

**Comment by kidzrockboom** [comment]
YAY IT worked with your method. I just followed the video. Thank you so much Man I appreciate it so much

**Comment by voussoir** [comment]
Great, I'm glad it worked 👍
